-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.client
(
    id serial NOT NULL,
    clientname character varying(255) COLLATE pg_catalog."default",
    cpf character varying(14) COLLATE pg_catalog."default",
    razaosocial character varying(255) COLLATE pg_catalog."default",
    cnpj character varying(18) COLLATE pg_catalog."default",
    telephone character varying(20) COLLATE pg_catalog."default",
    cellphone character varying(20) COLLATE pg_catalog."default",
    email1 character varying(255) COLLATE pg_catalog."default",
    email2 character varying(255) COLLATE pg_catalog."default",
    cep character varying(9) COLLATE pg_catalog."default",
    logradouro character varying(255) COLLATE pg_catalog."default",
    numero character varying(10) COLLATE pg_catalog."default",
    complemento character varying(255) COLLATE pg_catalog."default",
    brazilianstates character varying(2) COLLATE pg_catalog."default",
    city character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT client_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ordemservico
(
    id_ordem serial NOT NULL,
    data_inclusao date,
    hora_inclusao time without time zone,
    id_cliente integer,
    id_veiculo integer,
    id_tipo_ordem integer,
    CONSTRAINT ordemservico_pkey PRIMARY KEY (id_ordem)
);

CREATE TABLE IF NOT EXISTS public.statusordem
(
    id_status serial NOT NULL,
    id_ordem integer,
    data_alteracao date,
    hora_alteracao time without time zone,
    nome_status character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT statusordem_pkey PRIMARY KEY (id_status)
);

CREATE TABLE IF NOT EXISTS public.tipoordem
(
    id_tipo_ordem serial NOT NULL,
    id_ordem integer,
    id_servico integer,
    CONSTRAINT tipoordem_pkey PRIMARY KEY (id_tipo_ordem)
);

CREATE TABLE IF NOT EXISTS public.tiposervico
(
    id_servico serial NOT NULL,
    nome character varying(100) COLLATE pg_catalog."default",
    valor numeric(10, 2),
    CONSTRAINT tiposervico_pkey PRIMARY KEY (id_servico)
);

CREATE TABLE IF NOT EXISTS public.veiculo
(
    id serial NOT NULL,
    placa character varying(20) COLLATE pg_catalog."default" NOT NULL,
    cpf character varying(20) COLLATE pg_catalog."default" NOT NULL,
    cnpj character varying(20) COLLATE pg_catalog."default" NOT NULL,
    chassi character varying(50) COLLATE pg_catalog."default" NOT NULL,
    fabricante character varying(100) COLLATE pg_catalog."default" NOT NULL,
    modelo character varying(100) COLLATE pg_catalog."default" NOT NULL,
    cor character varying(50) COLLATE pg_catalog."default",
    ano_modelo integer,
    client_id integer,
    CONSTRAINT veiculo_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.ordemservico
    ADD CONSTRAINT fk_tipo_ordem FOREIGN KEY (id_tipo_ordem)
    REFERENCES public.tipoordem (id_tipo_ordem) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ordemservico
    ADD CONSTRAINT ordemservico_id_cliente_fkey FOREIGN KEY (id_cliente)
    REFERENCES public.client (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ordemservico
    ADD CONSTRAINT ordemservico_id_veiculo_fkey FOREIGN KEY (id_veiculo)
    REFERENCES public.veiculo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.statusordem
    ADD CONSTRAINT statusordem_id_ordem_fkey FOREIGN KEY (id_ordem)
    REFERENCES public.ordemservico (id_ordem) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tipoordem
    ADD CONSTRAINT tipoordem_id_ordem_fkey FOREIGN KEY (id_ordem)
    REFERENCES public.ordemservico (id_ordem) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tipoordem
    ADD CONSTRAINT tipoordem_id_servico_fkey FOREIGN KEY (id_servico)
    REFERENCES public.tiposervico (id_servico) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.veiculo
    ADD CONSTRAINT veiculo_client_id_fkey FOREIGN KEY (client_id)
    REFERENCES public.client (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;
