version: '3.8'

services:
  app:
    build: .
    ports:
      - '5010:5010'
    environment:
      - DATABASE_URL=postgres://postgres:Private@17@db:5432/car_automotive
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - '5434:5432'
    environment:
      POSTGRES_DB: car_automotive
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Private@17
